<a href="https://colab.research.google.com/github/VikaBilyk/numeric_methods/blob/main/lab2_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

def customSign(value):
    """реалізація для повернення знаку числа."""
    if value > 0:
        return 1
    elif value < 0:
        return -1
    return 0

def isSymmetric(matrix):
    """Перевірка симетричності матриці """
    n = len(matrix)
    for i in range(n):
        for j in range(i, n):
            if matrix[i][j] != matrix[j][i]:
                return False
    return True

def determinant_from_square_root_method(dMatrix, sMatrix):
    """Обчислення детермінанту через формулу квадратного кореня """
    n = dMatrix.shape[0]

    # Ініціалізуємо добутки для діагональних елементів
    prod_d = 1  # Добуток елементів dMatrix
    prod_s = 1  # Добуток квадратів елементів sMatrix

    # Обчислюємо добутки діагональних елементів
    for i in range(n):
        prod_d *= dMatrix[i][i]  # Добуток елементів dMatrix
        prod_s *= sMatrix[i][i] ** 2  # Добуток квадратів елементів sMatrix

    # Формула для детермінанту
    detA = prod_d * prod_s

    return detA


def squareRootMethod(aMatrix, bVector):

    # Перевірка на симетричність
    if not isSymmetric(aMatrix):
        raise ValueError("Матриця не є симетричною. Метод квадратного кореня можна застосовувати лише до симетричних матриць.")

    # Ініціалізуємо матриці D та S
    n = aMatrix.shape[0]
    dMatrix = np.zeros((n, n))
    sMatrix = np.zeros((n, n))

    # Обчислюємо елементи матриць D та S
    for i in range(n):
        # Обчислюємо суму для формули d_ii
        sum_s = 0
        for p in range(i):
            sum_s += sMatrix[p][p] ** 2 * dMatrix[p][p]

        # Обчислюємо d_ii
        dMatrix[i][i] = customSign(aMatrix[i][i] - sum_s)

        if i == 0:
            # Обчислюємо елементи першого рядка матриці S
            sMatrix[0][0] = np.sqrt(aMatrix[0][0])
            for j in range(1, n):
                sMatrix[0][j] = aMatrix[0][j] / sMatrix[0][0]

        else:
            # Обчислюємо s_ii для i > 0
            sMatrix[i][i] = np.sqrt(abs(aMatrix[i][i] - sum_s))

            for j in range(i + 1, n):
                # Обчислюємо sum_s для s_ij
                sum_s = 0
                for k in range(i):
                    sum_s += sMatrix[k][i] * dMatrix[k][k] * sMatrix[k][j]

                # Заповнюємо S для i = 2, ..., n-1 та j = i+1, ..., n
                if i > 0 and j > i:
                    sMatrix[i][j] = (aMatrix[i][j] - sum_s) / (dMatrix[i][i] * sMatrix[i][i])

    # Виводимо матрицю D
    print("Матриця D:")
    for row in dMatrix:
        print(row)

    # Виводимо матрицю S
    print("Матриця S:")
    for row in sMatrix:
        print(row)

    # Обчислюємо транспоновану матрицю S
    S_transpose = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            S_transpose[i][j] = sMatrix[j][i]

    # Обчислюємо StD
    StD = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            StD[i][j] = S_transpose[i][j] * dMatrix[i][i]

   # Обчислюємо детермінант через метод квадратного кореня
    detA = determinant_from_square_root_method(dMatrix, sMatrix)
    print("detA = Det(A) =", detA)

    y = np.zeros(n)

    # Дістаємо y
    for i in range(n):
        sum_y = 0
        for j in range(i):
            sum_y += StD[i][j] * y[j]
        y[i] = (bVector[i] - sum_y) / StD[i][i]

    x = np.zeros(n)

    # Зворотне підставлення для знаходження x
    for i in range(n - 1, -1, -1):
        sum_x = 0
        for j in range(i + 1, n):
            sum_x += sMatrix[i][j] * x[j]
        x[i] = (y[i] - sum_x) / sMatrix[i][i]

    return x

# Приклад
aMatrix = np.array([[1, 3, -2, 0, -2],
                    [3, 4, -5, 1, -3],
                    [-2, -5, 3, -2, 2],
                    [0, 1, -2, 5, 3],
                    [-2, -3, 2, 3, 4]])
bVector = np.array([0.5, 5.4, 5.0, 7.5, 3.3])

print("-----------Метод квадратного кореня-----------")
roots = squareRootMethod(aMatrix, bVector)
print("Корені:", roots)


-----------Метод квадратного кореня-----------
Матриця D:
[1. 0. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[ 0.  0. -1.  0.  0.]
[0. 0. 0. 1. 0.]
[ 0.  0.  0.  0. -1.]
Матриця S:
[ 1.  3. -2.  0. -2.]
[0.         1.73205081 0.57735027 0.57735027 1.73205081]
[0.         0.         1.         2.33333333 3.        ]
[0.         0.         0.         1.41421356 6.36396103]
[0. 0. 0. 0. 1.]
detA = Det(A) = 5.999999999999997
Корені: [-1773.55         154.89259259  -580.83611111   341.60833333
   -73.85      ]
