<a href="https://colab.research.google.com/github/VikaBilyk/numeric_methods/blob/main/lab2_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np

def customSqrt(value):
    """Власна реалізація для обчислення квадратного кореня."""
    if value < 0:
        raise ValueError("Квадратний корінь з від'ємного числа не визначений.")
    tolerance = 1e-10  # Точність
    guess = value / 2.0  # Початкове припущення
    while True:
        next_guess = (guess + value / guess) / 2
        if abs(next_guess - guess) < tolerance:
            return next_guess
        guess = next_guess

def customSign(value):
    """Власна реалізація для повернення знаку числа."""
    if value > 0:
        return 1
    elif value < 0:
        return -1
    return 0

def determinant(matrix):
    """Обчислення детермінанту матриці за допомогою методу мінорів."""
    n = len(matrix)
    if n == 1:
        return matrix[0][0]
    elif n == 2:
        return matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0]

    det = 0
    for c in range(n):
        sub_matrix = [[matrix[i][j] for j in range(n) if j != c] for i in range(1, n)]
        det += ((-1) ** c) * matrix[0][c] * determinant(sub_matrix)
    return det

def squareRootMethod(aMatrix, bVector, eps=0.001):
    # Ініціалізуємо матриці D та S
    n = aMatrix.shape[0]
    dMatrix = np.zeros((n, n))
    sMatrix = np.zeros((n, n))

    # Обчислюємо елементи матриць D та S
    for i in range(n):
        sum_s = 0
        for j in range(i):
            sum_s += sMatrix[j][i] * sMatrix[j][i] * dMatrix[j][j]

        # Будуємо матриці sMatrix та dMatrix
        dMatrix[i][i] = customSign(aMatrix[i][i] - sum_s)
        sMatrix[i][i] = customSqrt(abs(aMatrix[i][i] - sum_s))

        for j in range(i + 1, n):
            sum_s = 0
            for k in range(i):
                sum_s += sMatrix[k][i] * dMatrix[k][k] * sMatrix[k][j]
            sMatrix[i][j] = (aMatrix[i][j] - sum_s) / (dMatrix[i][i] * sMatrix[i][i])

    # Виводимо матрицю D
    print("Матриця D:")
    for row in dMatrix:
        print(row)

    # Виводимо матрицю S
    print("Матриця S:")
    for row in sMatrix:
        print(row)

    # Обчислюємо транспоновану матрицю S
    S_transpose = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            S_transpose[i][j] = sMatrix[j][i]

    # Обчислюємо StD
    StD = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            StD[i][j] = S_transpose[i][j] * dMatrix[i][i]

    # Рахуємо значення детермінанту StD
    detStD = determinant(StD)
    print("detA = Det(StD) =", detStD)

    y = np.zeros(n)

    # Дістаємо y
    for i in range(n):
        sum_y = 0
        for j in range(i):
            sum_y += StD[i][j] * y[j]
        y[i] = (bVector[i] - sum_y) / StD[i][i]

    x = np.zeros(n)

    # Зворотне підставлення для знаходження x
    for i in range(n - 1, -1, -1):
        sum_x = 0
        for j in range(i + 1, n):
            sum_x += sMatrix[i][j] * x[j]
        x[i] = (y[i] - sum_x) / sMatrix[i][i]

    return x

# Приклад
aMatrix = np.array([[1, 3, -2, 0, -2],
                    [3, 4, -5, 1, -3],
                    [-2, -5, 3, -2, 2],
                    [0, 1, -2, 5, 3],
                    [-2, -3, 2, 3, 4]])
bVector = np.array([0.5, 5.4, 5.0, 7.5, 3.3])

print("-----------Метод квадратного кореня-----------")
roots = squareRootMethod(aMatrix, bVector)
print("Корені:", roots)


-----------Метод квадратного кореня-----------
Матриця D:
[1. 0. 0. 0. 0.]
[ 0. -1.  0.  0.  0.]
[ 0.  0. -1.  0.  0.]
[0. 0. 0. 1. 0.]
[ 0.  0.  0.  0. -1.]
Матриця S:
[ 1.  3. -2.  0. -2.]
[ 0.          2.23606798 -0.4472136  -0.4472136  -1.34164079]
[0.         0.         0.89442719 2.01246118 1.56524758]
[0.         0.         0.         3.04138127 2.21938633]
[0.         0.         0.         0.         0.82199494]
detA = Det(StD) = -5.000000000000005
Корені: [-19.59702703  -9.82513514  -9.50621622  13.12054054 -15.28      ]
