<a href="https://colab.research.google.com/github/VikaBilyk/numeric_methods/blob/main/lab2_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np

def customSign(value):
    """реалізація для повернення знаку числа."""
    if value > 0:
        return 1
    elif value < 0:
        return -1
    return 0

def isSymmetric(matrix):
    """Перевірка симетричності матриці"""
    n = len(matrix)
    for i in range(n):
        for j in range(i, n):
            if matrix[i][j] != matrix[j][i]:
                return False
    return True

def determinant_from_square_root_method(dMatrix, sMatrix):
    """Обчислення детермінанту через формулу квадратного кореня"""
    n = dMatrix.shape[0]

    prod_d = 1  # Добуток елементів dMatrix
    prod_s = 1  # Добуток квадратів елементів sMatrix

    for i in range(n):
        prod_d *= dMatrix[i][i]  # Добуток елементів dMatrix
        prod_s *= sMatrix[i][i] ** 2  # Добуток квадратів елементів sMatrix

    detA = prod_d * prod_s

    return detA

def squareRootMethod(aMatrix, bVector, print_output=True):

    if not isSymmetric(aMatrix):
        raise ValueError("Матриця не є симетричною. Метод квадратного кореня можна застосовувати лише до симетричних матриць.")

    n = aMatrix.shape[0]
    dMatrix = np.zeros((n, n))
    sMatrix = np.zeros((n, n))

    for i in range(n):
        sum_s = 0
        for p in range(i):
            sum_s += sMatrix[p][p] ** 2 * dMatrix[p][p]

        dMatrix[i][i] = customSign(aMatrix[i][i] - sum_s)

        if i == 0:
            sMatrix[0][0] = np.sqrt(aMatrix[0][0])
            for j in range(1, n):
                sMatrix[0][j] = aMatrix[0][j] / sMatrix[0][0]

        else:
            sMatrix[i][i] = np.sqrt(abs(aMatrix[i][i] - sum_s))

            for j in range(i + 1, n):
                sum_s = 0
                for k in range(i):
                    sum_s += sMatrix[k][i] * dMatrix[k][k] * sMatrix[k][j]

                if i > 0 and j > i:
                    sMatrix[i][j] = (aMatrix[i][j] - sum_s) / (dMatrix[i][i] * sMatrix[i][i])

    if print_output:
        print("Матриця D:")
        for row in dMatrix:
            print(row)

        print("Матриця S:")
        for row in sMatrix:
            print(row)

    S_transpose = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            S_transpose[i][j] = sMatrix[j][i]

    StD = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            StD[i][j] = S_transpose[i][j] * dMatrix[i][i]

    detA = determinant_from_square_root_method(dMatrix, sMatrix)

    if print_output:
        print("detA = Det(A) =", detA)

    y = np.zeros(n)

    for i in range(n):
        sum_y = 0
        for j in range(i):
            sum_y += StD[i][j] * y[j]
        y[i] = (bVector[i] - sum_y) / StD[i][i]

    x = np.zeros(n)

    for i in range(n - 1, -1, -1):
        sum_x = 0
        for j in range(i + 1, n):
            sum_x += sMatrix[i][j] * x[j]
        x[i] = (y[i] - sum_x) / sMatrix[i][i]

    return x, S_transpose

def find_inverse_mtrx(R, S_t):
    Y = solve_inverse_mtrx(E=np.eye(5), R=R)
    X = solve_inverse_mtrx(Y, S_t)
    A_inv = np.zeros((5, 5), dtype=float)
    transposed_matrix(X, A_inv)
    return A_inv

def solve_inverse_mtrx(E, R):
    y = np.zeros(5)
    Y = np.zeros((5, 5), dtype=float)
    for j in range(5):
        y = solve_eq_mtrx(R, E[j])
        for i in range(5):
            Y[i][j] = y[i]
    return Y

def solve_eq_mtrx(R, b):
    n = len(b)
    y = np.zeros(n)
    for i in range(n):
        sum = 0
        for j in range(i):
            sum += R[i][j] * y[j]
        y[i] = (b[i] - sum) / R[i][i]
    return y

def transposed_matrix(S, S_transpose):
    for i in range(5):
        for j in range(5):
            S_transpose[i][j] = S[j][i]
    return

def matrix_norm_inf(A):
    """Обчислення норми матриці за максимумом суми абсолютних значень елементів по рядках."""
    n = len(A)
    max_sum = 0
    for i in range(n):
        row_sum = 0
        for j in range(n):
            row_sum += abs(A[i][j])
        if row_sum > max_sum:
            max_sum = row_sum
    return max_sum

def condition_number(A):
    """Обчислює число обумовленості матриці A."""
    norm_A = matrix_norm_inf(A)
    inv_A = find_inverse_mtrx(R=aMatrix, S_t=S_transpose)
    norm_inv_A = matrix_norm_inf(inv_A)
    return norm_A * norm_inv_A

# Використання
aMatrix = np.array([[1, 3, -2, 0, -2],
                    [3, 4, -5, 1, -3],
                    [-2, -5, 3, -2, 2],
                    [0, 1, -2, 5, 3],
                    [-2, -3, 2, 3, 4]])
bVector = np.array([0.5, 5.4, 5.0, 7.5, 3.3])

print("-----------Метод квадратного кореня-----------")
roots, S_transpose = squareRootMethod(aMatrix, bVector)

print("Корені:", roots)

A_inv = find_inverse_mtrx(R=aMatrix, S_t=S_transpose)

print("Обернена матриця:")
print(A_inv)

# Обчислення числа обумовленості
cond_A = condition_number(aMatrix)
print(f"Число обумовленості матриці A: {cond_A:.6f}")


-----------Метод квадратного кореня-----------
Матриця D:
[1. 0. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[ 0.  0. -1.  0.  0.]
[0. 0. 0. 1. 0.]
[ 0.  0.  0.  0. -1.]
Матриця S:
[ 1.  3. -2.  0. -2.]
[0.         1.73205081 0.57735027 0.57735027 1.73205081]
[0.         0.         1.         2.33333333 3.        ]
[0.         0.         0.         1.41421356 6.36396103]
[0. 0. 0. 0. 1.]
detA = Det(A) = 5.999999999999997
Корені: [-1773.55         154.89259259  -580.83611111   341.60833333
   -73.85      ]
Обернена матриця:
[[  1.          -1.73205081   3.          -4.24264069  23.        ]
 [ -0.75         1.44337567  -2.33333333   3.26054794 -17.75      ]
 [ -0.58333333   1.25092558  -1.55555556   2.05584749 -11.75      ]
 [ -0.08333333   0.2116951   -0.15555556   0.31165077  -2.05      ]
 [  0.29166667  -0.56772776   0.64444444  -0.93757121   5.85      ]]
Число обумовленості матриці A: 527.595064
